[package]
name = "awr-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
sha2.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml_ng.workspace = true
yaml-rust2.workspace = true
thiserror.workspace = true
ulid.workspace = true
globset.workspace = true
regex.workspace = true
base64.workspace = true
pulldown-cmark.workspace = true

[dev-dependencies]
serde_json.workspace = true
sha2.workspace = true
